name: stremio_jacket
services:
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Los_Angeles
#    networks:
#      - stremio_jacket_network
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Los_Angeles
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    depends_on:
      - flaresolverr
#    networks:
#      - stremio_jacket_network
    volumes:
      - ./data:/config
      - /path/to/blackhole:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
  jackett-stremio:
    image: belmeg/stremio-addon-jackett
    container_name: jackett-stremio
    environment:
      - PUID=$(id -u)
      - PGID=$(id -g)
      - TZ=America/Los_Angeles
      - ADDON_NAME=stremio_jacket
    depends_on:
      - jackett
#    networks:
#      - stremio_jacket_network
    ports:
      - 3000:3000
    restart: unless-stopped

#networks:
#    stremio_jacket_network:
#        external: true
#        name: stremio_jacket_network
