name: Build and push Docker image to Docker Hub
on:
  release:
    types: [created]
jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ— Checkout code
        uses: actions/checkout@v2

      - name: ğŸ— Setup Node.js environment
        uses: actions/setup-node@main
        with:
          node-version: 'lts/*'
          cache: 'npm'

      - name: ğŸš€ Build Docker image for arm64
        run: docker buildx build --platform linux/arm64 -t belmeg/stremio-addon-jackett:${{ github.event.release.tag_name }}-arm64 .

      - name: ğŸš€ Build Docker image for latest arm64
        run: docker buildx build --platform linux/arm64 -t belmeg/stremio-addon-jackett:${{ github.event.release.tag_name }}-arm64 .

      - name: ğŸš€ Build Docker image for amd64
        run: docker buildx build --platform linux/amd64 -t belmeg/stremio-addon-jackett:latest-amd64 .

      - name: ğŸš€ Build Docker image for latest arm64
        run: docker buildx build --platform linux/arm64 -t belmeg/stremio-addon-jackett:latest-arm64 .

      - name: ğŸ”’ Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ğŸ“© Push arm64 Docker image to Docker Hub
        run: docker push belmeg/stremio-addon-jackett:${{ github.event.release.tag_name }}-arm64

      - name: ğŸ“© Push latest arm64 Docker image to Docker Hub
        run: docker push belmeg/stremio-addon-jackett:latest-arm64

      - name: ğŸ“© Push amd64 Docker image to Docker Hub
        run: docker push belmeg/stremio-addon-jackett:${{ github.event.release.tag_name }}-amd64

      - name: ğŸ“© Push latest amd64 Docker image to Docker Hub
        run: docker push belmeg/stremio-addon-jackett:latest-amd64
